### ISSUE TITLE
Integrate examples using a test-suite

### ISSUE THREAD

**Issue by ichistmeinname** [Dagefoerde/muli-ST#7]

**Comment by Dagefoerde** [comment]
Done!

Many test cases that involve all our applications at https://github.com/Dagefoerde/muli-ST/tree/1b776e4eea1d99c39d71f3f2c99ab52741619d9f/src/test/java/search,
with automated execution by Travis CI https://travis-ci.org/Dagefoerde/muli-ST
and coverage reporting at https://codecov.io/gh/Dagefoerde/muli-ST.

(Ja, ist denn heut' schon September? :roll_eyes:  )
